config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  devise_for :users, controllers: {
    registrations: "users/registrations",
    passwords: "users/passwords"
  }
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
  root 'rooms#show'
  resources :messages, only: :create
  # get '/load_up', to: 'rooms#load_up'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user

  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 500 }

  # scope :load_old_messages, ->(number) { Message.includes(:user).order(:id).where(id: 1..last_id).last(50) }

  def template
    ApplicationController.render_with_signed_in_user(user, partial: 'messages/message', locals: { message: self })
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :messages, dependent: :destroy

  def self.guest
    find_or_create_by!(email: "guest@example.com") do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def self.render_with_signed_in_user(user, *args)
    ActionController::Renderer::RACK_KEY_TRANSLATION['warden'] ||= 'warden'
    proxy = Warden::Proxy.new({}, Warden::Manager.new({})).tap{ |i| i.set_user(user, scope: :user) }
    renderer = self.renderer.new('warden' => proxy)
    renderer.render(*args)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @message = current_user.messages.create!(message_params)
    ActionCable.server.broadcast 'room_channel', message: @message.template
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def show
    @messages = Message.includes(:user).order(:id)
    @message = current_user.messages.build
  end

  # def load_up
  #   last_id = params[:oldest_message_id].to_i - 1
  #   @messages = load_olod_messages(50)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  before_action :ensure_guest_user, only: :create

  def ensure_guest_user
    if params[:user][:email].downcase == "guest@example.com"
      redirect_to new_user_session_path, alert: "Guest user's password can't be reset"
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :ensure_guest_user, only: %i[update destroy]

  def ensure_guest_user
    if resource.email == "guest@example.com"
      redirect_to root_path, alert: "A guest user can't be updated or/and deleted."
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    sign_in User.guest
    redirect_to root_path, notice: "Logged in as a guest user"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def set_width
    if devise_controller?
      'mw-md'
    else
      'mw-xl'
    end
  end

  def bootstrap_devise_error_messages!
    return "" if resource.errors.empty?

    html = ""
    resource.errors.full_messages.each do |message|
      html+= <<-EOF
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">close</span>
        </button>
        #{error_message}
      </div>
      EOF
    end
    html.html_safe
  end
end

app/helpers/message_helper.rb
module MessageHelper
  def my_message?(message)
    message.user == current_user ? "yes" : "no"
  end
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |msg_type, msg| %>
  <div class="alert alert-<%= msg_type %>" role="alert" id="alert">
    <a href="#" class="close" data-dismiss="alert">×</a>
    <%= msg %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chatty Buddy</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <%= render 'layouts/flash_messages' %>
    <div class="container-fluid py-4 <%= set_width %>">
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="message mt-3 <%= my_message?(message) %>" id="message-<%= message.id %>">
  <div class="content-container">
    <div class="content">
      <%= simple_format(h message.content) %>
    </div>
    <div class="user">
      <%= message.user.email %>: <%= l message.created_at, format: :short %>
    </div>
  </div>
</div>

app/views/messages/create.js.erb
document.getElementById('message_content')
.value = '';

scrollToBottom();

app/views/rooms/_footer.html.erb
<footer class="fixed-bottom" id="footer">
  <%= form_with model: @message, local: false do |f| %>
    <div class="form-group">
      <%= f.text_area :content, class: 'form-control mb-2', rows: '1', maxlength: '500' %>
    </div>

    <div class="form-group">
      <%= f.submit 'Send', class: 'btn btn-primary form-control disabled', id: 'message-button' %>
    </div>
  <% end %>
</footer>

app/views/rooms/load_up.js.erb
<%# var messageHeight = messageContainer.scrollHeight %>

<%# messageContainer.insertAdjacentHTML('afterbegin', "j(render @messages)") %>

<%# var newMessageHeight = messageContainer.scrollHeight %>

<%# window.scrollBy(0, newMessageHeight - messageHeight) %>

<%# if @messages.present? %>
  <%# loadUp = true %>
<%# end %>

app/views/rooms/show.html.erb
<div id="message-container">
  <%= render @messages %>
  <%= render 'footer' %>
</div>

app/views/shared/_header.html.erb
<header class="sticky-top">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to "Catty Buddy", root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav">
          <% if user_signed_in? %>
            <li class="nav-item active nav-link">
              <small>Logged in as</small>
              <b><%= current_user.email %></b>
            </li>
            <li class="nav-item active">
              <%= link_to 'Edit account', edit_user_registration_path, class: 'nav-link' %>
            </li>
            <li class="nav-item active">
              <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'nav-link' %>
            </li>
          <% else %>
            <li class="nav-item active">
              <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
            </li>
            <li class="nav-item active">
              <%= link_to 'Login', new_user_session_path, method: :delete, class: 'nav-link' %>
            </li>
            <li class="nav-item active">
              <%= link_to 'Login As Guest', users_guest_sign_in_path, method: :post, class: 'nav-link' %>
            </li>
          <% end %>
        </ul>
      </div>
  </nav>
</header>